
SELECT PRODUCTO, NOMBRE_PRODUCTO, VALOR
FROM PRODUCTOS
WHERE VALOR > 1000

SELECT CF.CLIENTE, C.NOMBRE_CLIENTE, CF.TOTAL
FROM CABEZA_FACTURA CF
JOIN CLIENTES C
ON CF.CLIENTE = C.CLIENTE 


SET DATEFORMAT 'YMD'
SELECT CF.NUMERO,CL.NOMBRE_CLIENTE,CF.FECHA,PD.NOMBRE_PRODUCTO,DF.CANTIDAD,DF.VALOR
FROM DETALLE_FACTURA DF
JOIN CABEZA_FACTURA CF
ON DF.NUMERO = CF.NUMERO
JOIN CLIENTES CL
ON CL.CLIENTE = CF.CLIENTE
JOIN PRODUCTOS PD
ON DF.PRODUCTO = PD.PRODUCTO
WHERE CF.FECHA  >= CAST(N'2005-01-01 00:00:00.000' AS datetime) AND CAST (CF.FECHA AS datetime) <= CAST(N'2022-03-31 23:59:59.000' AS datetime)



SELECT CL.CLIENTE, CL.NOMBRE_CLIENTE
FROM CLIENTES CL
WHERE NOT EXISTS ( SELECT NULL 
				FROM CABEZA_FACTURA CF
				WHERE CF.CLIENTE = CL.CLIENTE
				)

SELECT PD.PRODUCTO,PD.NOMBRE_PRODUCTO, SUM(CANTIDAD) AS CANTIDAD
FROM DETALLE_FACTURA DF
JOIN PRODUCTOS PD
ON PD.PRODUCTO= DF.PRODUCTO
WHERE PD.PRODUCTO= DF.PRODUCTO
GROUP BY PD.NOMBRE_PRODUCTO , PD.PRODUCTO
ORDER BY CANTIDAD DESC

